import { createContext, useContext, useMemo, useState } from "react";

import { SelectColumn } from "../components/datagrid/Columns";

import DataGrid from "../components/datagrid/DataGrid";
import dropDownEditor from "../components/datagrid/editors/textEditor";
import { css } from "@linaria/core";
import textEditor from "../components/datagrid/editors/textEditor";

const highlightClassName = css`
  .rdg-cell {
    background-color: #9370db;
    color: white;
    position: sticky;
    top: 30px;
    z-index: 2;
  }

  &:hover .rdg-cell {
    background-color: #800080;
  }
`;
const FilterContext = createContext(undefined);

function rowKeyGetter(row) {
  return row.id;
}

export default function NoRows({ direction }) {
  const [selectedRows, onSelectedRowsChange] = useState(() => new Set());
  const [filters, setFilters] = useState({
    title: "",
    count: "",
    enabled: true,
  });

  const columns = useMemo(() => {
    return [
      SelectColumn,
      {
        field: "id",
        headerName: "ID",

        haveChildren: false,
        topHeader: "id",
        cellWidth: 60,
        frozen: true,
        summaryFormatter() {
          return <strong>Total</strong>;
        },
      },
      {
        field: "rdrd",
        headerName: "AASS",
        haveChildren: false,
        topHeader: "rdrd",
        cellWidth: 60,
        frozen: true,
        cellRenderer: dropDownEditor,
        editorOptions: {
          editOnClick: true,
        },
        summaryFormatter({ row }) {
          return <>{row.totalCount} records</>;
        },
      },
      {
        field: "rdsrd",
        headerName: "AASS",
        haveChildren: false,
        topHeader: "rdsrd",
        cellWidth: 60,
        frozen: true,
        // filter: true,
      },
    

      {
        field: "title",
        headerName: "Title",
        haveChildren: true,
        frozen: true,
        // cellWidth: 727,
        topHeader: "title",

        children: [
          // SelectColumn,
          {
            // frozen: true,
            field: "aaaa",
            headerName: "AAAA",

            haveChildren: true,
            children: [
              {
                field: "vvvv",
                headerName: "VVVV",
                haveChildren: false,
                cellWidth: 100,
                topHeader: "title",
                frozen: true,
                cellRenderer:textEditor,
                editorOptions: {
                  editOnClick: true,
                },
              },

              {
                field: "rrrr",
                headerName: "RRRR",
                haveChildren: false,
                cellWidth: 100,
                topHeader: "title",
                frozen: true,
              },
              {
                field: "uuuu",
                headerName: "UUUU",
                haveChildren: false,
                cellWidth: 100,
                topHeader: "title",
                frozen: true,
              },
            ],
          },
          {
            frozen: true,
            field: "bbbb",
            headerName: "BBBB",
            haveChildren: true,
            children: [
              {
                field: "wsdc",
                headerName: "HGTF",
                haveChildren: false,
                cellWidth: 100,
                topHeader: "title",
                frozen: true,
              },
              {
                field: "yugd",
                headerName: "HGFBGV",
                haveChildren: false,
                cellWidth: 100,
                topHeader: "title",
                frozen: true,
              },
            ],
          },
          {
            field: "cccc",
            headerName: "CCCC",
            
            haveChildren: true,
            topHeader: "title",
            frozen: true,
            children: [
              {
                field: "yuwgd",
                headerName: "HGFBGV",
                haveChildren: false,
                cellWidth: 100,
                topHeader: "title",
                frozen: true,
              },
              {
                field: "yqugd",
                headerName: "HGFBGV",
                haveChildren: true,
                topHeader: "title",
                
                frozen: true,
                children: [
                  {
                    field: "cvdcv",
                    headerName: "FGHT",
                    haveChildren: false,
                    topHeader: "title",
                    cellWidth: 60,
                    frozen: true,
                  },
                  {
                    field: "cvacv",
                    headerName: "FGHT",
                    haveChildren: false,
                    topHeader: "title",
                    cellWidth: 60,
                    frozen: true,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        field: "rdsrd11",
        headerName: "AASS",
        haveChildren: false,
        topHeader: "rdsrd11",
        cellWidth: 60,
        frozen: true,
      },
      {
        field: "erer",
        headerName: "FGHT",
        haveChildren: false,
        topHeader: "erer",
        cellWidth: 60,
        // frozen: true,
      },
      {
        field: "count",
        headerName: "Count",
        haveChildren: true,
        children: [
          // SelectColumn,
          {
            field: "nnnn",
            headerName: "NNNN",
            haveChildren: true,
            children: [
              {
                field: "xxxx",
                headerName: "XXXX",
                haveChildren: false,
                cellWidth: 100,
                topHeader: "count",
              },
              {
                field: "jjjj",
                headerName: "JJJJ",
                haveChildren: true,
                children: [
                  {
                    field: "ffff",
                    headerName: "FFFF",
                    haveChildren: false,
                    cellWidth: 100,
                    topHeader: "count",
                  },
                  {
                    field: "vvvv",
                    headerName: "VVVV",
                    haveChildren: true,
                    children: [
                      {
                        field: "llll",
                        headerName: "LLLL",
                        haveChildren: false,
                        cellWidth: 100,
                        topHeader: "count",
                      },
                      {
                        field: "pppp",
                        headerName: "PPPP",
                        haveChildren: true,
                        children: [
                          {
                            field: "eee2e",
                            headerName: "EEEE",
                            haveChildren: false,
                            cellWidth: 100,
                            topHeader: "count",
                          },
                          {
                            field: "pppp",
                            headerName: "PPPP",
                            haveChildren: true,
                            cellWidth: 100,
                            topHeader: "count",
                            children: [
                              {
                                field: "ee6ee",
                                headerName: "EEEE",
                                haveChildren: false,
                                cellWidth: 100,
                                topHeader: "count",
                                
                              },
                              {
                                field: "pppp",
                                headerName: "PPPP",
                                haveChildren: true,

                                topHeader: "count",
                                children: [
                                  {
                                    field: "ee6ee",
                                    headerName: "EEEE",
                                    haveChildren: false,
                                    cellWidth: 100,
                                    topHeader: "count",
                                    cellRenderer:textEditor,
                editorOptions: {
                  editOnClick: true,
                },
                                  },
                                  {
                                    field: "pppp",
                                    headerName: "PPPP",
                                    haveChildren: false,
                                    cellWidth: 100,
                                    topHeader: "count",
                                    cellRenderer:textEditor,
                editorOptions: {
                  editOnClick: true,
                },
                                  },
                                ],
                              },
                            ],
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            field: "oooo",
            headerName: "OOOO",
            cellWidth: 100,
            haveChildren: false,
            topHeader: "count",
          },
          {
            field: "qqqq",
            headerName: "QQQQ",
            cellWidth: 100,
            haveChildren: false,
            topHeader: "count",
          },
        ],
      },
    ];
  }, []);

  const rowss = [
    {
      id: 1,
      oooo: "JGRF",
      aaaa: "wsws",
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",rdsrd:"ererer"
    },
    {
      id: 2,
      oooo: "JGRF",
      aaaa: "wsws",
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",rdsrd:"frtrtr"
    },
    {
      id: 3,
      oooo: "JGRF",
      aaaa: "wsws",
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",rdsrd:"ghhtyt"
    },
    {
      id: 4,
      vvvv: "assdd",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",rdsrd:"eertr"
    },
    {
      id: 5,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",rdsrd:"qwqwqw"
    },
    {
      id: 6,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrr: "wrerer",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",rdsrd:"trtrt"
    },
    {
      id: 7,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 8,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 9,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 10,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 11,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 12,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 13,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 14,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 15,
      vvvv: "Ssss",
      nnnn: "gege",
      ccrcc: "dfhhgh",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 16,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 17,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 18,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 19,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 20,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 21,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 22,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 23,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 24,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 25,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 26,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 27,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 28,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 29,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 30,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 31,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 32,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 33,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 34,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 35,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 36,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 37,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 38,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 39,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 40,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 41,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 42,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 43,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
    {
      id: 44,
      vvvv: "Ssss",
      nnnn: "gege",
      qqqq: "kjkj",
      llll: "llll",
      rrrrr: "thgf",
      uuuu: "iugy",
      bbbb: "vfvf",
      cccc: "sdsd",
      xxxx: "sdsa",
      ffff: "aqaq",
      eeee: "tyty",
      pppp: "frfr",
    },
  ];

  const [rows, setRows] = useState(rowss);
  

  const summaryRows = useMemo(() => {
    const summaryRow = {
      id: "total_0",
      totalCount: rows.length,
      yesCount: rows.filter((r) => r.id).length,
    };
    return [summaryRow];
  }, [rows]);

  const selectedCellHeaderStyle = {
    backgroundColor: 'red',
    fontSize: "12px"
  }
  function handlePaste({
    sourceColumnKey,
    sourceRow,
    targetColumnKey,
    targetRow,
  }) {
    const incompatibleColumns = ["email", "zipCode", "date"];
    if (
      sourceColumnKey === "avatar" ||
      ["id", "avatar"].includes(targetColumnKey) ||
      ((incompatibleColumns.includes(targetColumnKey) ||
        incompatibleColumns.includes(sourceColumnKey)) &&
        sourceColumnKey !== targetColumnKey)
    ) {
      return targetRow;
    }

    return { ...targetRow, [targetColumnKey]: sourceRow[sourceColumnKey] };
  }

  function handleCopy({ sourceRow, sourceColumnKey }) {
    if (window.isSecureContext) {
      navigator.clipboard.writeText(sourceRow[sourceColumnKey]);
    }
  }

  return (
    // <FilterContext.Provider value={filters}>
    <DataGrid
      columnData={columns}
      rowData={rows}
      onRowsChange={setRows}
      onFill={true}
      onCopy={handleCopy}
      onPaste={handlePaste}
      // rowHeight={30}
      headerRowHeight={24}
      summaryRowHeight={24}
      selectedCellHeaderStyle={selectedCellHeaderStyle}
      selectedRows={selectedRows}
      // onSelectedRowsChange={setSelectedRows}
      rowFridgeIndexEnd={7}
      topSummaryRows={summaryRows}
      // bottomSummaryRows={summaryRows}
      singleRowFridgeIndex={11}
      // direction={direction}
    />
    // </FilterContext.Provider>
  );
}
